version: '3'
services:
  jupyterlab:
    build: .
    image: jupyterlab-img
    container_name: jupyterlab-container
    working_dir: /work
    volumes:
      - ./work:/work
      - ./app:/app
    ports:
      - "8888:8888"
      - "8000:8000"
    command:
      jupyter-lab --ip 0.0.0.0 --allow-root -b localhost
      
      
      
